version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${USER}
      POSTGRES_USER: ${PASSWORD}
      POSTGRES_DB: ${DB}
    ports:
      - '5432:5432'
    volumes:
      - web_db_data:/var/lib/postgresql/data
    restart: always

  web:
    build: 
      context: .
      dockerfile: compose/Dockerfile
    env_file:
      - ./env/local.env
    ports:
    - '5000:5000'
    entrypoint: compose/docker-entrypoint.sh
    depends_on:
      - db
    restart: always

volumes:
  web_db_data: